/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package View;

import DAO.DAOClienteEspecial;
import DAO.DAOMedicamentos;
import Model.Medicamento;
import Model.ModelClienteEspecial;
import java.awt.event.ItemEvent;
import java.sql.SQLException;
import java.text.DecimalFormat;
import java.util.Vector;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.DefaultComboBoxModel;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import javax.swing.text.MaskFormatter;



/**
 *
 * @author Sabrina
 */
public class FormVenda extends javax.swing.JFrame {
    
    Medicamento med;
    boolean desconto = false;
    double valorCDesconto = 0;
    double total = 0;
    double Dcliente = 0;
    double troco = 0;
    double valorTotal = 0;
    
    DAOClienteEspecial DAOcliente = new DAOClienteEspecial();
    
    DAOMedicamentos DAOmed = new DAOMedicamentos();

    DefaultComboBoxModel<Medicamento> model = 
            new DefaultComboBoxModel<Medicamento>();
    
    DefaultTableModel modelTB = new DefaultTableModel();
    Object[] columns = {"IUM","NOME", "VALOR"};
    
    /**
     * Creates new form FormVenda
     */
    public FormVenda() {
        initComponents();
        preencherCombo();
        
        DefaultTableModel tabela=(DefaultTableModel)tbVenda.getModel();
        
        
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        btnPesquisar = new javax.swing.JButton();
        lbIUMCB = new javax.swing.JLabel();
        txtIdCb = new javax.swing.JTextField();
        btnExcluir1 = new javax.swing.JButton();
        lblVenda = new javax.swing.JLabel();
        cbMedicamento = new javax.swing.JComboBox<>();
        lblIum = new javax.swing.JLabel();
        lbIUMCB1 = new javax.swing.JLabel();
        lblNome = new javax.swing.JLabel();
        lbIUMCB2 = new javax.swing.JLabel();
        lblValor = new javax.swing.JLabel();
        lbIUMCB3 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        txtCpf = new javax.swing.JTextField();
        lblValorTotal1 = new javax.swing.JLabel();
        lblValorTotal2 = new javax.swing.JLabel();
        lblValorTotal = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tbVenda = new javax.swing.JTable();
        btnAdicionar = new javax.swing.JButton();
        lblDesconto = new javax.swing.JLabel();
        btnDesconto = new javax.swing.JButton();
        btnConfirmarVenda = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setForeground(java.awt.Color.white);

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));

        btnPesquisar.setBackground(new java.awt.Color(255, 255, 255));
        btnPesquisar.setFont(new java.awt.Font("Rockwell", 1, 14)); // NOI18N
        btnPesquisar.setForeground(new java.awt.Color(0, 204, 204));
        btnPesquisar.setText("Pesquisar");
        btnPesquisar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnPesquisarActionPerformed(evt);
            }
        });

        lbIUMCB.setFont(new java.awt.Font("Rockwell", 1, 14)); // NOI18N
        lbIUMCB.setForeground(new java.awt.Color(0, 204, 204));
        lbIUMCB.setText("Adicionar Medicamento:");

        txtIdCb.setFont(new java.awt.Font("Rockwell", 0, 14)); // NOI18N
        txtIdCb.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                txtIdCbFocusLost(evt);
            }
        });

        btnExcluir1.setBackground(new java.awt.Color(255, 255, 255));
        btnExcluir1.setFont(new java.awt.Font("Rockwell", 1, 14)); // NOI18N
        btnExcluir1.setForeground(new java.awt.Color(0, 204, 204));
        btnExcluir1.setText("Voltar");
        btnExcluir1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnExcluir1ActionPerformed(evt);
            }
        });

        lblVenda.setFont(new java.awt.Font("Rockwell", 3, 24)); // NOI18N
        lblVenda.setForeground(new java.awt.Color(0, 102, 102));
        lblVenda.setText("Venda");

        cbMedicamento.setFont(new java.awt.Font("Rockwell", 0, 14)); // NOI18N
        cbMedicamento.setForeground(new java.awt.Color(0, 204, 204));
        cbMedicamento.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                cbMedicamentoItemStateChanged(evt);
            }
        });
        cbMedicamento.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cbMedicamentoActionPerformed(evt);
            }
        });

        lblIum.setFont(new java.awt.Font("Rockwell", 1, 14)); // NOI18N
        lblIum.setForeground(new java.awt.Color(0, 204, 204));
        lblIum.setText("-----");

        lbIUMCB1.setFont(new java.awt.Font("Rockwell", 1, 14)); // NOI18N
        lbIUMCB1.setForeground(new java.awt.Color(0, 204, 204));
        lbIUMCB1.setText("IUM");

        lblNome.setFont(new java.awt.Font("Rockwell", 1, 14)); // NOI18N
        lblNome.setForeground(new java.awt.Color(0, 204, 204));
        lblNome.setText("----");

        lbIUMCB2.setFont(new java.awt.Font("Rockwell", 1, 14)); // NOI18N
        lbIUMCB2.setForeground(new java.awt.Color(0, 204, 204));
        lbIUMCB2.setText("Nome");

        lblValor.setFont(new java.awt.Font("Rockwell", 1, 14)); // NOI18N
        lblValor.setForeground(new java.awt.Color(0, 204, 204));
        lblValor.setText("----");

        lbIUMCB3.setFont(new java.awt.Font("Rockwell", 1, 14)); // NOI18N
        lbIUMCB3.setForeground(new java.awt.Color(0, 204, 204));
        lbIUMCB3.setText("Preço Unitário");

        jLabel1.setFont(new java.awt.Font("Rockwell", 1, 14)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(0, 204, 204));
        jLabel1.setText("Identificação");

        txtCpf.setFont(new java.awt.Font("Rockwell", 0, 14)); // NOI18N

        lblValorTotal1.setFont(new java.awt.Font("Rockwell", 1, 14)); // NOI18N
        lblValorTotal1.setForeground(new java.awt.Color(0, 204, 204));
        lblValorTotal1.setText("Valor Compra:");

        lblValorTotal2.setFont(new java.awt.Font("Rockwell", 1, 14)); // NOI18N
        lblValorTotal2.setForeground(new java.awt.Color(0, 204, 204));
        lblValorTotal2.setText("Valor Desconto:");

        lblValorTotal.setFont(new java.awt.Font("Rockwell", 1, 14)); // NOI18N
        lblValorTotal.setForeground(new java.awt.Color(0, 204, 204));
        lblValorTotal.setText("valorParcial");

        tbVenda.setFont(new java.awt.Font("Rockwell", 0, 14)); // NOI18N
        tbVenda.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "IUM", "NOME", "VALOR"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, true
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane1.setViewportView(tbVenda);

        btnAdicionar.setBackground(new java.awt.Color(255, 255, 255));
        btnAdicionar.setFont(new java.awt.Font("Rockwell", 1, 14)); // NOI18N
        btnAdicionar.setForeground(new java.awt.Color(0, 204, 204));
        btnAdicionar.setText("Adicionar");
        btnAdicionar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAdicionarActionPerformed(evt);
            }
        });

        lblDesconto.setFont(new java.awt.Font("Rockwell", 1, 14)); // NOI18N
        lblDesconto.setForeground(new java.awt.Color(0, 204, 204));
        lblDesconto.setText("desconto");

        btnDesconto.setBackground(new java.awt.Color(255, 255, 255));
        btnDesconto.setFont(new java.awt.Font("Rockwell", 1, 14)); // NOI18N
        btnDesconto.setForeground(new java.awt.Color(0, 204, 204));
        btnDesconto.setText("Checar Desconto");
        btnDesconto.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnDescontoActionPerformed(evt);
            }
        });

        btnConfirmarVenda.setBackground(new java.awt.Color(255, 255, 255));
        btnConfirmarVenda.setFont(new java.awt.Font("Rockwell", 1, 14)); // NOI18N
        btnConfirmarVenda.setForeground(new java.awt.Color(0, 204, 204));
        btnConfirmarVenda.setText("Finalizar");
        btnConfirmarVenda.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnConfirmarVendaActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(14, 14, 14)
                        .addComponent(btnExcluir1)
                        .addGap(710, 710, 710))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addContainerGap(718, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(lblVenda)))
                .addGap(0, 0, Short.MAX_VALUE))
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 2, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(jLabel1)
                                .addGap(8, 8, 8)
                                .addComponent(txtCpf, javax.swing.GroupLayout.PREFERRED_SIZE, 111, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(lblValorTotal2)
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 2, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(lblValorTotal1)))
                                .addGap(18, 18, 18)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(lblValorTotal)
                                    .addComponent(lblDesconto)))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(35, 35, 35)
                                .addComponent(btnAdicionar, javax.swing.GroupLayout.PREFERRED_SIZE, 115, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(11, 11, 11)
                                .addComponent(btnDesconto, javax.swing.GroupLayout.PREFERRED_SIZE, 167, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 13, Short.MAX_VALUE)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 603, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(btnConfirmarVenda, javax.swing.GroupLayout.PREFERRED_SIZE, 115, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addGroup(jPanel1Layout.createSequentialGroup()
                                    .addGap(151, 151, 151)
                                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(lblNome)
                                        .addComponent(lbIUMCB2))
                                    .addGap(117, 117, 117)
                                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(lbIUMCB3)
                                        .addComponent(lblValor)
                                        .addComponent(btnPesquisar)))
                                .addComponent(lblIum)
                                .addComponent(lbIUMCB1))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(lbIUMCB)
                                .addGap(18, 18, 18)
                                .addComponent(txtIdCb, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(27, 27, 27)
                                .addComponent(cbMedicamento, javax.swing.GroupLayout.PREFERRED_SIZE, 51, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(118, 118, 118)))
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(btnExcluir1)
                .addGap(3, 3, 3)
                .addComponent(lblVenda)
                .addGap(29, 29, 29)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lbIUMCB)
                    .addComponent(txtIdCb, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(cbMedicamento, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnPesquisar))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lbIUMCB1)
                    .addComponent(lbIUMCB2)
                    .addComponent(lbIUMCB3))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(lblNome)
                        .addComponent(lblValor))
                    .addComponent(lblIum))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(btnAdicionar, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(lblDesconto)
                            .addComponent(lblValorTotal2))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(lblValorTotal1)
                            .addComponent(lblValorTotal))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(txtCpf, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel1))
                        .addGap(18, 18, 18)
                        .addComponent(btnDesconto, javax.swing.GroupLayout.PREFERRED_SIZE, 46, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 202, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 11, Short.MAX_VALUE)
                .addComponent(btnConfirmarVenda, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnConfirmarVendaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnConfirmarVendaActionPerformed
        // TODO add your handling code here:
        JOptionPane.showMessageDialog(null, "Venda Realizada com Sucesso!");
        dispose();
    }//GEN-LAST:event_btnConfirmarVendaActionPerformed

    private void cbMedicamentoItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_cbMedicamentoItemStateChanged
        // TODO add your handling code here:
        if(evt.getStateChange() == ItemEvent.SELECTED) {
            Medicamento m = (Medicamento)evt.getItem();
            txtIdCb.setText(m.getId());
        }
    }//GEN-LAST:event_cbMedicamentoItemStateChanged

    private void cbMedicamentoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cbMedicamentoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cbMedicamentoActionPerformed

    
    private void calculaTotal(){
    total = valorTotal;
    
    DecimalFormat formato = new DecimalFormat("#.##");      
        Double preco = Double.valueOf(formato.format(total));
    lblValorTotal.setText(Double.toString((preco)));
    }
    
    
    private void btnPesquisarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnPesquisarActionPerformed
        try {
            
            
            //cria um objeto
            Medicamento m = new Medicamento();

            //joga o codigo a ser pesquisado para o obj filme
            m.setId(txtIdCb.getText());

            // faz a procura
            m = DAOmed.buscar(m);

            if(m != null) {
            lblIum.setText(m.getId());
            lblNome.setText(m.getNome());
            lblValor.setText(Double.toString(m.getValor()));
            
            }

            else {
                JOptionPane.showMessageDialog(this,
                    "Medicamento não encontrado!",
                    "Mensagem ao Usuário",
                    JOptionPane.INFORMATION_MESSAGE);
            }

        } catch (SQLException ex) {
            Logger.getLogger(FormClienteEspecial.class.getName()).log(Level.SEVERE, null, ex);

        } catch (ClassNotFoundException ex) {
            Logger.getLogger(FormClienteEspecial.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_btnPesquisarActionPerformed

    private void txtIdCbFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtIdCbFocusLost
        // TODO add your handling code here:
        if(txtIdCb.getText().length() > 0) {
            Medicamento m = new Medicamento();
            m.setId(txtIdCb.getText());
            //deixa a combo com nada selecionado
            cbMedicamento.setSelectedIndex(-1);
            //faz a procura
            cbMedicamento.setSelectedItem(m);
        }
    }//GEN-LAST:event_txtIdCbFocusLost

    private void btnAdicionarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAdicionarActionPerformed
        // TODO add your handling code here:
        modelTB.setColumnIdentifiers(columns);
        
        tbVenda.setModel(modelTB);
        
        Object[] row = new Object[3];
        row[0] = lblIum.getText();
        row[1] = lblNome.getText();
        row[2] = lblValor.getText();
        
        modelTB.addRow(row);
        
        valorTotal += Double.valueOf(lblValor.getText());
        
        
        if(desconto){
            
            valorCDesconto = valorTotal * 0.9;
            
            DecimalFormat formato = new DecimalFormat("#.##");      
            
            Double preco = Double.valueOf(formato.format(total));
            
            lblDesconto.setText(Double.toString((valorTotal * 0.1)));
            lblValorTotal.setText(Double.toString(valorCDesconto));
            calculaTotal();
        }else{
            lblValorTotal.setText(Double.toString(valorTotal));
            calculaTotal();
        }
        
    }//GEN-LAST:event_btnAdicionarActionPerformed

    private void btnDescontoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDescontoActionPerformed
        // TODO add your handling code here:
        try {
        ModelClienteEspecial c = new ModelClienteEspecial();
        
        c.setCpf(txtCpf.getText());
        
        c = DAOcliente.buscar(c);
        
        if(c != null) { //achou
                //permitir desconto
                JOptionPane.showMessageDialog(this, 
                        "Desconto Autorizado!",
                        "Mensagem ao Usuário",
                        JOptionPane.INFORMATION_MESSAGE);
                valorCDesconto = valorTotal * 0.9;
                lblDesconto.setText(Double.toString((valorTotal * 0.1)));
                lblValorTotal.setText(Double.toString(valorCDesconto));
                desconto = true;
                txtCpf.setEnabled(false);
                calculaTotal();
            }
            else {
                JOptionPane.showMessageDialog(this, 
                        "Cliente não Encontrado!",
                        "Mensagem ao Usuário",
                        JOptionPane.INFORMATION_MESSAGE);
                //habilitaInicio();
                txtCpf.requestFocus();
                txtCpf.setText("");
                calculaTotal();
            }
        } catch (SQLException ex) {
                        JOptionPane.showMessageDialog(this,
                        "Erro SQL " + ex.getMessage(),
                        "Mensagem ao Usuário",
                        JOptionPane.ERROR_MESSAGE);
            //Logger.getLogger(GerenciamentoCliente.class.getName()).log(Level.SEVERE, null, ex);
        } catch (ClassNotFoundException ex) {
            Logger.getLogger(FormVenda.class.getName()).log(Level.SEVERE, null, ex);
        }
        
        
        
    }//GEN-LAST:event_btnDescontoActionPerformed

    private void btnExcluir1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnExcluir1ActionPerformed
        // TODO add your handling code here:
        dispose();
    }//GEN-LAST:event_btnExcluir1ActionPerformed
    
    private void preencherCombo() {
        Vector<Medicamento> dados;
        DAOMedicamentos DAOmed = new DAOMedicamentos();
        try {
            dados = (Vector)DAOmed.listar("");
            model = new DefaultComboBoxModel<>(dados);
            cbMedicamento.setModel(model);
            
            
            
        } catch (SQLException ex) {
            JOptionPane.showMessageDialog(this, 
                    "Erro de SQL na Combo: " + ex.getMessage(),
                    "Mensagem ao Usuario",
                    JOptionPane.ERROR_MESSAGE);
        } catch (ClassNotFoundException ex) {
            JOptionPane.showMessageDialog(this, 
                    "Erro de Classe na Combo " + ex.getMessage(),
                    "Mensagem ao Usuario",
                    JOptionPane.ERROR_MESSAGE);
        }
    }
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(FormVenda.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(FormVenda.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(FormVenda.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(FormVenda.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new FormVenda().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAdicionar;
    private javax.swing.JButton btnConfirmarVenda;
    private javax.swing.JButton btnDesconto;
    private javax.swing.JButton btnExcluir1;
    private javax.swing.JButton btnPesquisar;
    private javax.swing.JComboBox<Medicamento> cbMedicamento;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel lbIUMCB;
    private javax.swing.JLabel lbIUMCB1;
    private javax.swing.JLabel lbIUMCB2;
    private javax.swing.JLabel lbIUMCB3;
    private javax.swing.JLabel lblDesconto;
    private javax.swing.JLabel lblIum;
    private javax.swing.JLabel lblNome;
    private javax.swing.JLabel lblValor;
    private javax.swing.JLabel lblValorTotal;
    private javax.swing.JLabel lblValorTotal1;
    private javax.swing.JLabel lblValorTotal2;
    private javax.swing.JLabel lblVenda;
    private javax.swing.JTable tbVenda;
    private javax.swing.JTextField txtCpf;
    private javax.swing.JTextField txtIdCb;
    // End of variables declaration//GEN-END:variables
}
